# Generated by Django 4.1.7 on 2023-06-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_follows'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follows',
            new_name='Follow',
        ),
    ]
