# Generated by Django 4.1.7 on 2023-06-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_rename_follows_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='following_user_id',
            new_name='following_user',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='user_id',
            new_name='user',
        ),
    ]
