# Generated by Django 4.1.7 on 2023-06-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
