# Generated by Django 4.1.7 on 2023-08-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0002_delete_tag_remove_activity_tags_activity_game_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='method',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='activity',
            name='required_materials',
            field=models.CharField(default=None, max_length=180),
        ),
    ]
