# Generated by Django 4.1.7 on 2023-08-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0007_alter_activity_age_range_alter_activity_game_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='required_materials',
            field=models.CharField(blank=True, default=None, max_length=180),
        ),
    ]
