# Generated by Django 4.1.7 on 2023-09-05 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0010_alter_activity_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='likes',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='scout.like'),
            preserve_default=False,
        ),
    ]
