# Generated by Django 4.1.7 on 2023-09-05 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0012_alter_activity_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='likes',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='scout.like'),
        ),
    ]
